services:
  genmap:
    image: ghcr.io/sv3t0v1k/genmap:latest
    build: .
    ports:
      - "127.0.0.1:8080:80"
    networks:
      - npm_proxy-network
    restart: unless-stopped

networks:
  npm_proxy-network:
    external: true
